config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'

  post '/' => 'home#create'
  get '/base_information' => 'home#base_information'
  post '/create_base_information' => 'home#create_base_information'
  get '/domicile' => 'home#domicile'
  post '/create_domicile' => 'home#create_domicile'
  get '/document' => 'home#document'
  post '/create_document' => 'home#create_document'
  get '/result' => 'home#result'
  post '/complete_issue' => 'home#complete_issue'
end

app/controllers/home_controller.rb
require 'json'
class HomeController < ApplicationController
  include ApiCall

  after_action :create_issue, only: [:create]

  def index
    @email = ''
  end

  def create
    @email = create_params[:email]
    session[:email] = @email
    if session[:account].present?
      @account = session[:account]
    else
      @account = get_userid_by_email(@email)
      @account = set_account(@email)['id'] if @account.nil?
      session[:account] = @account
    end
    redirect_to base_information_path and return
  rescue StandardError => e
    reset_session
    redirect_to root_path, error: e.message and return
  end

  def base_information; end

  def create_base_information
    @email_seed = create_email_seeds(session[:issue], session[:email])
    @natural_docket_seed = create_natural_docker_seed(session[:issue], create_params[:first_name], create_params[:last_name],
                                                      create_params[:birth_date], create_params[:nationality])
    redirect_to domicile_path and return
  rescue StandardError => e
    reset_session
    redirect_to root_path, error: e.message and return
  end

  def domicile; end

  def create_domicile
    @domicile_seed = create_domicile_seeds(session[:issue], create_params[:country], create_params[:state], create_params[:city],
                                           create_params[:street_address], create_params[:street_number], create_params[:postal_code])
    @address_img = create_attachments(@domicile_seed['id'], 'domicile_seeds', create_params[:address_img])
    raise StandardError, 'Address image error' if @address_img.nil?

    redirect_to document_path and return
  rescue StandardError => e
    redirect_to domicile_path, e.message and return
  end

  def document; end

  def create_document
    @document = identification_seed(session[:issue], create_params[:document], 'ar')
    @document_img = create_attachments(@document['id'], 'identification_seeds', create_params[:document_img])
    raise StandardError, @document_img if @document_img.nil?

    redirect_to result_path and return
  rescue StandardError => e
    redirect_to document_path, error: e.message and return
  end

  def result; end

  def complete_issue
    @issue_complete = issue_complete(session[:issue])
    reset_session unless @issue_complete.present?
    redirect_to result_path and return
  rescue StandardError => e
    redirect_to result_path, error: e.message and return
  end

  private

  def create_params
    params.permit(:authenticity_token, :commit, :controller, :action,
                  :first_name, :last_name, :birth_date, :nationality, :document,
                  :document_img, :email, :message, :address_img,
                  :country, :state, :city, :street_address, :street_number, :postal_code,
                  address: %i[country state city street_address street_number postal_code floor apartment])
  end

  def create_issue
    session[:issue] = create_issue(session[:account])['id'] unless session[:issue].present?
  rescue StandardError => e
    reset_session
    flash.now[:error] = e.message
    e.message
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/base_information.html.erb
<div class="dark:bg-gray-800 w-full p-6 rounded shadow">
  <%= form_with(url: create_base_information_path, method: "post") do |form| %>
    <div class="grid lg:grid-cols-2 lg:gap-6">
      <div class="relative z-0 w-full mb-6 group">
        <%= form.label :first_name, 'Nombre', class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
        <%= form.text_field :first_name, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
      </div>
      <div class="relative z-0 w-full mb-6 group">
        <%= form.label :last_name, 'Apellido', class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
        <%= form.text_field :last_name, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
      </div>
    </div>
    <div class="relative z-0 w-full mb-6 group">
      <%= form.label :birth_date, 'Fecha de Nacimiento', class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
      <%= form.date_field :birth_date, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
    </div>
    <div class="relative z-0 w-full mb-6 group">
      <%= form.label :nationality, 'Nacionalidad', class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
      <%= form.select :nationality, [["Argentina", "ar"], ["Chile", 'cl']], class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
    </div>

    <div>
      <%= form.submit 'Enviar', class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>
    </div>
  <% end %>
  <% flash.each do |type, msg| %>
    <div class="text-red-500 text-sm font-medium">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/home/document.html.erb
<div class="dark:bg-gray-800 w-full p-6 rounded shadow">
  <%= form_with(url: create_document_path, method: "post") do |form| %>
    <div class="relative z-0 w-full mb-6 group">
      <%= form.label :document, 'Documento', class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
      <%= form.number_field :document, in: 1000000..999999999, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
    </div>
    <div class="relative z-0 w-full mb-6 group">
      <%= form.label :document_img, 'Imagen del Documento', class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300' %>
      <%= form.file_field :document_img, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' %>
    </div>

    <div>
      <%= form.submit 'Enviar', class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>
    </div>
  <% end %>
  <% flash.each do |type, msg| %>
    <div class="text-red-500 text-sm font-medium">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/home/domicile.html.erb
<div class="dark:bg-gray-800 w-full p-6 rounded shadow">
  <%= form_with(url: create_domicile_path, method: "post") do |form| %>    
    <div class="grid lg:grid-cols-2 lg:gap-6">      
      <div class="relative z-0 w-full mb-6 group">
        <%= form.label :country, 'Pais', class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
        <%= form.select :country, [["Argentina", "ar"], ["Chile", 'cl']], class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
      </div>

      <div class="relative z-0 w-full mb-6 group">
        <%= form.label :state, 'Provincia', class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
        <%= form.text_field :state, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
      </div>

      <div class="relative z-0 w-full mb-6 group">
        <%= form.label :city, 'Ciudad', class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
        <%= form.text_field :city, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
      </div>

      <div class="relative z-0 w-full mb-6 group">
        <%= form.label :street_address, 'Calle', class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
        <%= form.text_field :street_address, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
      </div>

      <div class="relative z-0 w-full mb-6 group">
        <%= form.label :street_number, 'Número de calle', class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
        <%= form.text_field :street_number, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
      </div>

      <div class="relative z-0 w-full mb-6 group">
        <%= form.label :postal_code, 'Codigo postal', class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
        <%= form.text_field :postal_code, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
      </div>

      <div class="relative z-0 w-full mb-6 group">
        <%= form.label :address_img, 'Comprobante de domicilio', class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300' %>
        <%= form.file_field :address_img, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' %>
      </div>
    </div>

    <div>
      <%= form.submit 'Enviar', class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>
    </div>
  <% end %>
  <% flash.each do |type, msg| %>
    <div class="text-red-500 text-sm font-medium">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="dark:bg-gray-800 w-full p-6 rounded shadow">
  <%= form_with do |form| %>

    <div class="relative z-0 w-full mb-6 group">
      <%= form.label :email, class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
      <%= form.email_field :email, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
    </div>

    <div>
      <%= form.submit 'Enviar', class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>
    </div>
  <% end %>
  <% flash.each do |type, msg| %>
    <div class="text-red-500 text-sm font-medium">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/home/result.html.erb
<div class="bg-gray-600">
<%= button_to "Completar", complete_issue_path, method: :get, class: 'bg-gray-900 py-4 px-2 rounded' %>
</div>
<% flash.each do |type, msg| %>
  <div class="text-red-500 text-sm font-medium">
    <%= msg %>
  </div>
<% end %>